In [1]:
import numpy as np

In [2]:
array = np.array(range(5))

array

array([0, 1, 2, 3, 4])

In [3]:
type(array)

numpy.ndarray

In [4]:
array_2d = np.array([range(5), range(5)])

array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [5]:
array.ndim

1

In [6]:
array_2d.ndim

2

In [7]:
array.shape

(5,)

In [8]:
array_2d.shape

(2, 5)

In [9]:
array.size

5

In [10]:
array_2d.size

10

In [11]:
array.dtype

dtype('int32')

In [12]:
np.array(['I', 'love', 'Python'])

array(['I', 'love', 'Python'], dtype='<U6')

U6 refers to the length of the longest string in the array

### **Array Creation**

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
ar = np.ones(9, dtype='int')
ar

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
ar.reshape(3, 3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
np.zeros(100, 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((3, 20), 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [21]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [23]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

linspace is kinda tricky, you need plus 1 to the step of your desired length if you start from 0

In [24]:
np.linspace(8, 64, 8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

In [25]:
np.linspace(0, 64, 8)

array([ 0.        ,  9.14285714, 18.28571429, 27.42857143, 36.57142857,
       45.71428571, 54.85714286, 64.        ])

In [26]:
np.linspace(0, 64, 9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

In [27]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### **Random Number**

In [28]:
rng = np.random.default_rng(616)

rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [29]:
rng.integers(0, 10, 100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5], dtype=int64)

In [30]:
rng.normal(50, 5, 10)

array([53.53115044, 46.35468178, 46.1580894 , 52.89177118, 45.90693639,
       44.51748741, 57.41467712, 51.82624671, 53.9032125 , 53.21454641])

### **Indexing and Slicing**

In [31]:
integer_array = np.arange(12).reshape(3, 4)
integer_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
integer_array[1, 1]

5

In [33]:
integer_array[2, 3]

11

In [34]:
integer_array[-1, -1]

11

In [35]:
integer_array[:, 3]

array([ 3,  7, 11])

In [36]:
integer_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
integer_array[2:, 1:]

array([[ 9, 10, 11]])

In [38]:
integer_array[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

### **Array Operations**

In [39]:
rng = np.random.default_rng(616)

In [40]:
inventory = rng.integers(0, 100, 10)

In [41]:
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [42]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [43]:
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [44]:
price = (rng.random(10) * 10).round(2)
price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [45]:
inventory * price

array([ 34.71, 343.98, 680.76, 629.52, 269.76, 156.4 ,  30.24, 107.1 ,
        22.33, 245.67])

In [46]:
(inventory * price).sum()

2520.4700000000003

### **Filtering Arrays and Modifying Array Values**

In [47]:
my_array = np.arange(20)

my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [49]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
even_odd = np.array(['even', 'odd'] * 10)

even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [51]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [52]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [53]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
my_array[even_odd != 'odd'] = 0

In [55]:
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

### **Where**

In [56]:
my_array = np.arange(20)

my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
np.where(my_array % 2 == 0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [58]:
np.where(my_array % 2 == 0, 'even', np.where(my_array == 9, my_array, 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U11')